name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: 'true'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Cache browsers
        id: browser_cache
        uses: actions/cache@v3
        with:
          path: '~/.cache/ms-playwright'
          key: chromium-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ steps.browser_cache.outputs.cache-hit == 'true' }}
      - run: pnpm build
      - run: pnpm test
        env:
          CHOKIDAR_USEPOLLING: '1'
          TSC_WATCHFILE: 'DynamicPriorityPolling'
