name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: 'true'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18]
    name: Build & Test (Node v${{ matrix.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Cache browsers
        id: browser_cache
        uses: actions/cache@v3
        with:
          path: '~/.cache/ms-playwright'
          key: chromium-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - run: pnpx playwright install --with-deps
        if: steps.browser_cache.outputs.cache-hit != 'true'
      - run: pnpm build
      - run: pnpm test
        env:
          CHOKIDAR_USEPOLLING: '1'
          TSC_WATCHFILE: 'DynamicPriorityPolling'
